import {
  Home,
  BookOpen,
  GraduationCap,
  Users,
  DollarSign,
  Building2,
  BarChart3,
  MessageSquare,
  Bell,
  CalendarDays,
} from 'lucide-react';

export const PRINCIPAL_MENU_ITEMS = [
  {
    id: 'overview',
    label: 'Dashboard Overview',
    description: 'School-wide statistics and KPIs',
    path: '/principal/overview',
    icon: Home,
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-600',
  },
  {
    id: 'academics',
    label: 'Academic Analytics',
    description: 'Performance, grades, and curriculum',
    path: '/principal/academics',
    icon: BookOpen,
    iconBg: 'bg-violet-100',
    iconColor: 'text-violet-600',
  },
  {
    id: 'students',
    label: 'Student Analytics',
    description: 'Enrollment, attendance, and progress',
    path: '/principal/students',
    icon: GraduationCap,
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-600',
  },
  {
    id: 'staff',
    label: 'Staff Management',
    description: 'Teachers, performance, and HR',
    path: '/principal/staff',
    icon: Users,
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-600',
  },
  {
    id: 'finance',
    label: 'Financial Dashboard',
    description: 'Revenue, fees, and expenses',
    path: '/principal/finance',
    icon: DollarSign,
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-600',
  },
  {
    id: 'facilities',
    label: 'Facilities',
    description: 'Buildings, floors, and rooms',
    path: '/principal/facilities',
    icon: Building2,
    iconBg: 'bg-pink-100',
    iconColor: 'text-pink-600',
  },
  {
    id: 'reports',
    label: 'Reports',
    description: 'Academic, attendance & financial summary',
    path: '/principal/reports',
    icon: BarChart3,
    iconBg: 'bg-sky-100',
    iconColor: 'text-sky-600',
  },
  {
    id: 'communications',
    label: 'Communications',
    description: 'Directory, announcements, and chat',
    path: '/principal/communications',
    icon: MessageSquare,
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-600',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Alerts and urgent matters',
    path: '/principal/notifications',
    icon: Bell,
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-600',
  },
  {
    id: 'calendar',
    label: 'Calendar',
    description: 'Holidays and exam dates',
    path: '/principal/calendar',
    icon: CalendarDays,
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-600',
  },
];
